
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: joshua_hub_development

test:
  <<: *default
  database: joshua_hub_test

production:
  <<: *default
  database: joshua_hub_production

